version: "3.9"

services:

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  postfixadmin:
    depends_on:
      - db
    image: postfixadmin
    ports:
      - 9000:80
    restart: always
    environment:
      POSTFIXADMIN_DB_TYPE: mysqli
      POSTFIXADMIN_DB_HOST: db
      POSTFIXADMIN_DB_USER: ${POSTFIXADMIN_DB_USER}
      POSTFIXADMIN_DB_NAME: ${POSTFIXADMIN_DB_NAME}
      POSTFIXADMIN_DB_PASSWORD: ${POSTFIXADMIN_DB_PASSWORD}
      POSTFIXADMIN_SMTP_SERVER: ${POSTFIXADMIN_SMTP_SERVER}
      POSTFIXADMIN_SETUP_PASSWORD: ${POSTFIXADMIN_SETUP_PASSWORD}

  postfix-dovecot:
    container_name: "postfix-dovecot"
    image: "humpedli/docker-postfix-dovecot"
    ports:
      - "25:25"
      - "587:587"
      - "993:993"
    volumes:
      - "${PATH_TO_CERT}:/etc/ssl/certs/fullchain.pem:ro"
      - "${PATH_TO_KEY}:/etc/ssl/private/privkey.pem:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      HOSTNAME: ${HOST_DOMAIN}
      CUSTOM_NETWORKS: 172.18.0.0/16
      POSTMASTER: ${POSTMASTER_EMAIL}
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - db
    restart: "always"

volumes:
  db-data:
    external: true